activitystreams2-context.jsonld, activitystreams2-vocabulary.html, activitystreams2.html, activitystreams2.owl
The instrument, participant and status properties have very little real world justification for inclusion in the core vocabulary based on an analysis of relevant use cases. I recommend dropping these.
=> Remove instrument, participant and status from vocabulary

activitystreams2-vocabulary.html
There are many cases in social systems where third party identities are associated with the main identity (e.g. linking facebook and twitter accounts to a user account). Unfortunately, there are no existing common models or standards to draw on in terms of how these are represented after the fact. Introducing Identity, Claim and proof provide a way.
```json
{
"@type": "Claim",
"actor": "acct:sally@example.org",
"object": {
"@type": "Identity", 
"@id": "acct:sally@example.net"
},
"proof": {
"@type": "...",
"@value": "..."
}
}
```
=> Adding Identity, Claim and proof

activitystreams2.owl
noticed in #65 
validated with https://github.com/mmlab/TurtleValidator
=> made activitystreams2.owl pass turtle-validator

activitystreams2-context.jsonld, activitystreams2.html
GeoSparql uses gsp prefix, not geos
* http://prefix.cc/gsp
* http://lov.okfn.org/dataset/lov/vocabs/gsp
=> gsp - recommended prefix for GeoSparql

activitystreams2.html
the proposal is to add a profile media type parameter to both media types. it would allow profiles to be identified at the media type level. profiles according to RFC 6906 could be used to signal certain vocabularies that an activity stream may use (or that a client prefers). https://github.com/dret/ASDL is one way how such a profile could be represented (currently ASDL is focusing on AS1), but the profile parameter would not require a specific representation, or any at all. it would simply signify that an activity stream follows a profile.
=> adding profile media type parameter

activitystreams2-vocabulary.html, activitystreams2.html
rather than publish another WD with incorrect and
non-normative microformats examples, simply remove
them. If we want to define a normative microformats
mapping in a separate document, then we can still do
so. Having incorrect non-normative examples is not
helpful.
=> remove microformats examples

activitystreams2-context.jsonld, activitystreams2-vocabulary.html, activitystreams2.html, activitystreams2.owl
To reduce confusion, remove the "Post" activity and clearly
indicate that "Create" and "Add" replace the original function
of the AS1 "post" verb. Provide clear deprecation and handling
advice.
=> remove the Post activity

activitystreams2-context.jsonld, activitystreams2-vocabulary.html, activitystreams2.html, activitystreams2.owl
The "Share" activity creates some confusion. In many common
cases, a "Share" is really just a normal post targeted at
specific people, which can be accomplished using the audience
targeting mechanism along with "Announce". Removing "Share"
allows us to eliminate a confusing element in the vocabulary.
=> remove "Share"

activitystreams2-context.jsonld, activitystreams2-vocabulary.html, activitystreams2.owl
remove the "Give" activity type. We have "Offer" which is a
more generalized form and there are no user stories supporting
keeping "Give" in the core vocabulary
=> remove "Give"

activitystreams2-context.jsonld, activitystreams2-vocabulary.html, activitystreams2.owl
The "Save" activity is functionally equivalent to
"Add". None of our user stories support having a
separate "Save" that is distinct from "Add".
=> remove "Save"

activitystreams2-context.jsonld, activitystreams2-vocabulary.html, activitystreams2.owl
The "Respond" activity type was added speculatively as a
superclass of a set of more specific Activity types like
"Like", "Dislike", etc. Since it was added, the decision
was made not to require support for inferencing, making
it largely unnecessary to define a hierarchy of responses.
None of our user stories justify having a separate generic
"Respond" activity and we already have "in-reply-to" as
a property.
=> remove "Respond"

activitystreams2-vocabulary.html, activitystreams2.html, activitystreams2.owl
the audience targeting properties have been limited
to Activities up to this point. This allows those
properties to be defined on any Object, as has been
requested by several WG members.
=> move audience targeting properties to Object

activitystreams2.html
Putting "Social" in quotes feels like it's introducing more questions than needed. We know that there's a Social Web Working Group, so talking about social Web applications isn't that questionable. I lowercased "Social" to "social" since I think we're talking about a common noun (social application using the Web) rather than a proper noun (application on the Social Web).
=> "Social" Web -> social Web

activitystreams2-vocabulary.html
Lowercased and &lt;code&gt;d the name of the actor property to differentiate
it from the Actor class.
=> Lowercase and <code> for actor

activitystreams2.html
Correct the plural of "Object".
=> common to all Object's -> common to all Objects

activitystreams2-vocabulary.html, activitystreams2.html
Per issue #79 this replaces all URNs with URLs.  I am not switching
these examples to https however.  In practice I have found suggesting
https puts (however minor) extra work on implementors.
I would suggest perhaps an authors note to say that while all examples
are http:// URLs, https:// URLs, URNs, and acct: are all options for
ids and other such values.  Perhaps including that urls are recommended.
=> Replaces all URNs with URLs in examples.

activitystreams2-context.jsonld, activitystreams2-vocabulary.html, activitystreams2.owl
as:Like and as:Favorite overlap and are confusing.
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/174
This removes as:Favorite
=> remove as:Favorite

activitystreams-vocabulary/index.html
Changes to some mf2 examples to remove *-as-* prefixes where it was possible to bring them inline with current usage patterns.
=> Update mf2 examples

activitystreams-core/activitystreams2-context.jsonld, activitystreams-core/index.html, activitystreams-vocabulary/activitystreams2.owl, activitystreams-vocabulary/index.html
Remove Content:
* Simplifies and flattens the vocabulary
* height and width are limited to as:Link and are defined specifically
as rendering hints
* Everything that previously derived from Content now derives
directly from Object. (this has the side effect of eliminating
the somewhat weird multiple inheritance on the Question object)
* duration property is removed from as:Link, it was just weird
there. It's moved up to Object so that any Object can have a
duration
=> Another round of batched updates

core/index.html
Vocabulary does describe id property as "Provides the globally unique identifier for an Object or Link."
But it's ambiguous reading core whether that's ok, since it's omitted from this section.
This pull resolves https://github.com/w3c/activitystreams/issues/288
=> Clarify in core that Links can have 'id'

core/index.html
Adds a few additional lines of JSON so it's clearer why one might need to use these different ways of presenting the `@context`
=> Update context examples

implementation-reports/distbin.com, implementation-reports/template.md
Distbin's public collection supports paging including limiting the items per page via max-member-count querystring parameter or [Prefer header argument defined in LDP Paging](https://www.w3.org/2012/ldp/hg/ldp-paging.html#ldpp-hints).
e.g. to page through by 2: http://distbin.com/public?max-member-count=2
Pro tip: You can use the collection renderer to render on distbin.com to render (and page through) other CollectionPages by using the `?page=url` querystring parameter.
e.g. http://distbin.com/public?page=https://rawgit.com/gobengo/171d9774382c31850ecf03a8a5611fac/raw/bc35d935705ee1a4199eaa2db1679192e44ccb1c/page1.json
=> distbin.com paging & startIndex in impl report template

implementation-reports/distbin.com
On distbin.com you can now specify a URL to attach to your post. If that resource prefers to respond as Content-Type: image/something, it will be rendered on the activity's HTML page.
http://distbin.com/activities/bdc12eca-07d7-44de-ac01-e060a4a887a6
=> Update distbin.com impl report to use .attachment and .mediaType

implementation-reports/distbin.com
When creating an activity, you can use the [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation) to specify your coordinates and/or you can just type a .location.name.
If a .location is provided, a globe appears when the activity is rendered. You can click on the globe to see a map of the .location.
Example: https://distbin.com/activities/d74ec7aa-f98a-44d6-81df-a6b598086cf8
=> distbin.com implements .location, Place

vocabulary/index.html
Should be editorial since it doesn't break implementations, but permits the range to match examples (which use a date).  I'd also be okay with datetime only.
=> Add datetime and boolean to range of "closed" property

vocabulary/index.html
From description, clearly meant to be a dateTime.
This shoud be just an editorial change; it's clear from the description that a timestamp is meant, and the current range is just a typo.
=> Fix typo in deleted range

core/activitystreams1-context.jsonld
As these terms were removed from the as2 context recently
https://github.com/w3c/activitystreams/commit/65ea6c58ad543d73c98ab78d1e096e1338f7a7b4
Related to #375
=> Add attachments, tags, author to as1-context

ns/activitystreams.jsonld, ns/index.html
Add the vcard: prefix to the context document to make it easier for people to use vcard: terms. Note: this ''does not'' include aliases for vcard terms, since that has less support.
=> Add vcard: prefix to context document; closes #459

ns/activitystreams.jsonld, ns/index.html
... see issue #511.
In the absence of a formal extensibility processes. I would like to discuss this at a SocialCG meeting at some point.
This property is used in multiple implementations (including Mastodon and Zot) who already assume it is available in the `as` namespace. There is some other discussion of this property [on socialhub](https://socialhub.activitypub.rocks/t/defining-alsoknownas/907) by other implementers of the property.
=> Extension: alsoKnownAs from DID Core

.github/workflows/fep-explainer.yml
This should help to explain what Needs FEP means, and why issues labelled with it may be closed.
Note: This requires a `GITHUB_TOKEN` secret to be set on the repository.
This is based on this [guide from GitHub](https://docs.github.com/en/actions/use-cases-and-examples/project-management/commenting-on-an-issue-when-a-label-is-added).
=> Add GitHub Action that automatically comments on issues labelled as Needs FEP
