w3c/activitystreams

.gitignore
package.json
tests/examples.js
tests/helper.js

replaces #67 on @jasnell request
related to work in #65

added basics for testing graph isomorphism

---

activitystreams2.html
package.json
tests/examples.js
tests/helper.js

I fixed examples 1 & 3 and would like to get some feedback before moving on with it, so no need to merge it until i fix all the other turtle examples!
you can run
```shell
npm test
```
rel #65

Fixing Turtle examples

---

activitystreams2.html

As a start, fixing first couple of microformats examples to be consistent with typical real world publishing practices. For issue 83: https://github.com/jasnell/w3c-socialwg-activitystreams/issues/83
In process of addressing SWWG Action 26: https://www.w3.org/Social/track/actions/26

fix first couple of microformats examples

---

activitystreams2-vocabulary.html

Per http://www.w3.org/Social/track/issues/29
This leaves Arrive and Travel for now.

remove Reservation, Claim, Achieve, and proof

---

activitystreams2-vocabulary.html
activitystreams2.html
activitystreams2.owl

Resolution for http://www.w3.org/Social/track/issues/35
Simplify the Actor types.

Simplify the actor types

---

activitystreams2-context.jsonld
activitystreams2-vocabulary.html
activitystreams2.html
activitystreams2.owl

Lack of clear interest. Developers have ways of adding these back in
via extensions if they need them

Remove inverse properties from vocabulary

---

activitystreams2.owl

Fixes a syntax error in turtle serialization of the vocabulary.

---

activitystreams2-context.jsonld
activitystreams2-vocabulary.html
activitystreams2.owl

per: https://github.com/jasnell/w3c-socialwg-activitystreams/issues/113

remove watch

---

activitystreams2-vocabulary.html
activitystreams2.owl

per: https://github.com/jasnell/w3c-socialwg-activitystreams/issues/114

make Read a subclass of Experience

---

activitystreams2-context.jsonld
activitystreams2-vocabulary.html
activitystreams2.owl

per: https://github.com/jasnell/w3c-socialwg-activitystreams/issues/112#issuecomment-103623614

add describes property to Profile object

---

activitystreams2-context.jsonld
activitystreams2-vocabulary.html
activitystreams2.owl

per https://github.com/jasnell/w3c-socialwg-activitystreams/issues/115

remove Confirm

---

activitystreams2-context.jsonld
activitystreams2-vocabulary.html
activitystreams2.owl

The "Review" Activity type has always been a bit wonky
and there are other vocabularies that do a better job.
None of our user stories require this to be in the core
vocabulary.

remove "Review"

---

activitystreams2-vocabulary.html
activitystreams2.html

git rebase not as easy when you do proper merging, so I am abandoning previous PR (https://github.com/jasnell/w3c-socialwg-activitystreams/pull/139) for a single change PR

Fix Microformats2 examples

---

activitystreams2.html

This didn't read correctly; I tried to update it to what I think the intended meaning was.

Grammar correction in section 3

---

activitystreams2.html

Possessive form of "it" in English is "its".

it's own -> its own

---

activitystreams2.html

Unless "listing" has a technical meaning I don't understand, I think a reference to the classic data structure is probably valuable here.

listing -> list

---

activitystreams2-vocabulary.html

Removed second "that" in a list of three comma-delimited items.

Parallelism in list

---

activitystreams2-vocabulary.html
activitystreams2.html

change all <link> tags to <a> tags

refs #80, change links to a href

---

activitystreams2-context.jsonld
activitystreams2-vocabulary.html
activitystreams2.html
activitystreams2.owl

per: https://github.com/jasnell/w3c-socialwg-activitystreams/issues/153

re-add organization

---

activitystreams2.html

https://github.com/jasnell/w3c-socialwg-activitystreams/issues/159
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/160
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/162
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/171
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/172
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/173

multiples fixes

---

activitystreams2-vocabulary.html

https://github.com/jasnell/w3c-socialwg-activitystreams/issues/180
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/179
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/178
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/177
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/176

several improvements

---

activitystreams2.html

per: https://github.com/jasnell/w3c-socialwg-activitystreams/issues/158
Not a big change, may need to do more.

clarify properties a bit

---

activitystreams-vocabulary/index.html

Per "Clarification of as:content" email discussion

Propose dfn of as:content, add data-lt to properties list

---

core/index.html
vocabulary/index.html

Multiple commits to address the i18n WG feedback
/cc @evanp

Address i18n concerns

---

core/index.html

Per the i18n discussion last week... /cc @rhiaro @evanp @r12a

Updating bidi details

---

implementation-reports/activipy.md
implementation-reports/pubstrate.md
implementation-reports/soci-el.md

Implementation reports for soci-el, activipy, and pubstrate

Implementation reports

---

implementation-reports/socialstreams.md

This is just the current status, I hope to add more features and will update this as I continue.

initial pass at social streams implementation report

---

core/index.html

Update OA and PROV use in examples

---

implementation-reports/distbin.com

http://distbin.com/public (other instances available at http://{a,b,c}.distbin.com)

create distbin.com implementation report

---

implementation-reports/distbin.com

example: https://distbin.com/activities/2bfc362c-9e54-4e7a-987a-4f4782f763fe

distbin.com implements .tag

---

core/index.html
vocabulary/index.html

first, last, current Domain clarifications

---

implementation-reports/distbin.com
implementation-reports/template.md

Add href to implementation report template. Resolves #401

---

implementation-reports/activitystream-extension.md

this line missing is what was breaking the implementation reports generator.

missing Implemented: line on object

---

README.md

lol @rhiaro https://github.com/w3c/activitystreams/commit/20de2467f4a492f415b4a5bbef303ff6f107d4c9#diff-04c6e90faac2675aa89e2176d2eec7d8R1

Fix typo in header of README.md
